bpm_statement = "Blender Project Manager --- "
opening_statement = bpm_statement + "Opening "
back_to_edit_statement = bpm_statement + "Opening Editing Project "
startup_statement = bpm_statement + "Looking for Project Datas"
loaded_datas_statement = bpm_statement + "Project Datas loaded"
loaded_folders_statement = bpm_statement + "Project Folders loaded"
no_datas_statement = bpm_statement + "Project Datas not found"
loading_statement = bpm_statement + "Project Datas found, loading from "
folders_loading_statement = bpm_statement + "Project Folders found, loading from "
currently_loading_statement = bpm_statement + "Currently loading "

file_project = "project_data.json"
custom_folders_file = "project_custom_folders.json"